# Generated by Django 4.0.1 on 2022-01-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='name',
            new_name='text',
        ),
    ]
